mysql:
  host: localhost
  port: 3306
  username: root
  password: root

elasticsearch:
  host: localhost
  port: 9300

tables:
  - test.user
  - test.post

tableInfo:
  - tableName: test.user
    aliasName: test-index.user-index
    columns:
      - id
      - name
      - location
    columnInfo:
      - columnName: id
        aliasName: _id
